kind: pipeline
name: i5sing_website_deploy

trigger:
  ref:
    - refs/heads/master
    - refs/tags/v*
steps:
  - name: build_docker_image
    image: plugins/docker
    settings:
      repo: i5sing/i5sing-website
      auto_tag: true
      username:
        from_secret: docker_repository_username
      password:
        from_secret: docker_repository_password
    when:
      branch:
        exclude:
          - master
  - name: deploy_on_kubernetes
    image: zfeng/drone-kube
    settings:
      namespace: default
      server:
        from_secret: k8s_kube_server
      token:
        from_secret: k8s_kube_token
      ca:
        from_secret: k8s_kube_ca
      template: deployment.yaml
  - name: wechat
    image: lizheming/drone-wechat
    settings:
      corpid:
        from_secret: wechat_corp_id
      corp_secret:
        from_secret: wechat_corp_secret
      agent_id:
        from_secret: wechat_agent_id
      to_user: ZhaoFeng
      to_tag: ${DRONE_REPO_NAME}
      msg_url: ${DRONE_BUILD_LINK}
      safe: 1
      btn_txt: more
      title: ${DRONE_REPO_NAME}
      message: >
        {%if success %}
          build {{build.number}} succeeded. Good job.
        {% else %}
          build {{build.number}} failed. Fix me please.
        {% endif %}
    when:
      status:
        - success
        - failure
