kind: pipeline
name: default

steps:
  - name: build docker image
    image: plugins/docker
    settings:
      repo: i5sing/i5sing-website
      auto_tag: true
      username:
        from_secret: docker_repository_username
      password:
        from_secret: docker_repository_password
  - name: deploy on kubernetes
    image: vallard/drone-kube
    settings:
      namespace: default
      server: https://172.21.0.1
