kind: pipeline
name: default

steps:
  - name: build_docker_image
    image: plugins/docker
    settings:
      repo: i5sing/i5sing-website
      auto_tag: true
      username:
        from_secret: docker_repository_username
      password:
        from_secret: docker_repository_password
  - name: deploy_on_kubernetes
    image: vallard/drone-kube
    settings:
      namespace: default
      server:
        from_secret: k8s_kube_server
      token:
        from_secret: k8s_kube_token
