server:
  development:
    port: 3033
  production:
    port: 3033

mysql:
  development:
    host: example.com
    user: username
    password: password
    connectionLimit: 20
    queueLimit: 500
    database: i5sing
    port: 3306
  production:
    host: example.com
    user: username
    password: password
    connectionLimit: 20
    queueLimit: 500
    database: i5sing
    port: 3306
qiniu:
  bucket: i5sing
  access_key: qiniukey
  secret_key: qiniukey