server:
  development:
    port: 3033
  production:
    port: 3033

mysql:
  development:
    host: 127.0.0.1
    user: root
    password: root
    connectionLimit: 20
    queueLimit: 500
    database: i5sing-web
    port: 3317
  production:
    host: 127.0.0.1
    user: root
    password: root
    connectionLimit: 20
    queueLimit: 500
    database: i5sing-web
    port: 3306