server:
  development:
    port: 3033
  production:
    port: 3033

mysql:
  development:
    host: localhost
    user: root
    password: root
    connectionLimit: 20
    queueLimit: 500
    database: i5sing
    port: 3306
  production:
    host: localhost
    user: root
    password: root
    connectionLimit: 20
    queueLimit: 500
    database: i5sing
    port: 3306
qiniu:
  bucket: i5sing
  access_key: access_key
  secret_key: secret_key